lib-y	+= grid.o interpol_fun.o vector_copy.o
lib-y 	+= Object/Object.o Node/node.o grid/grid.o \
	implicitForm/implicitForm.o surface/surface.o \
	surface/surfaceSphere/surfacesphere.o surface/surfaceTorus/surfaceTorus.o
obj-y	+= Object/ Node/ grid/ implicitForm/ surface/
clean-files := *.o *~ *.d
