obj-y	+= u0.o u_sphere.o u0_Torus.o dumbell.o
clean-files := *.o *~ *.d

# Enable Profiling Data
#-----------------------------------------------------------------------------
ifeq ($(strip $(OPTIONS)),-pg)
cflags-y += -pg
endif